apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-spectrum-scale-fileset
provisioner: csi-spectrum-scale
parameters:
    volBackendFs: "gpfs1"
    clusterId: "7118073361626808055"
    uid: "1000"
    gid: "1000"
    fileset-type: "dependent"
    dependentFileset: "pvc-9c93ffc6-b113-47b4-bbb4-29306f567f2b"
reclaimPolicy: Delete
